language: nix
notifications:
  email:
  - false
  
script:
- nix-build

deploy:
  local-dir: result
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  #keep-history: true
  on:
    branch: master
